// Enrich data/stocks.json with sector + short description.
// Best-effort: explicit overrides for well-known names, then keyword-based
// inference, then a clean fallback. We never silently make up business facts.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(__filename), "..");
const file = path.join(root, "data", "stocks.json");
const stocks = JSON.parse(fs.readFileSync(file, "utf8"));

// Hand-curated overrides for prominent constituents. Keep these short.
const overrides = {
  "AcadeMedia": ["Consumer Services", "Sweden's largest private education provider, running pre-schools, upper-secondary and adult education."],
  "Actic Group": ["Consumer Services", "Nordic gym and fitness club operator."],
  "Active Biotech": ["Health Care", "Swedish biotech developing immunomodulators for cancer and autoimmune disease."],
  "AddLife B": ["Health Care", "Distributor of medical-technology and lab products across the Nordics."],
  "Addnode Group B": ["Technology", "IT solutions group focused on design, product lifecycle and public-sector software."],
  "AFRY": ["Industrials", "Nordic engineering and consultancy firm (energy, infrastructure, industry)."],
  "Aktia Pankki": ["Financials", "Finnish retail and private bank."],
  "AL Sydbank": ["Financials", "Danish full-service bank."],
  "Alimak Group": ["Industrials", "Vertical-access solutions (industrial lifts, hoists, BMUs)."],
  "ALK-Abelló B": ["Health Care", "Danish global leader in allergy immunotherapy."],
  "Alleima": ["Materials", "Advanced stainless steel and special-alloy producer (former Sandvik Materials)."],
  "Alligator Bioscience": ["Health Care", "Swedish immuno-oncology biotech."],
  "Alligo B": ["Industrials", "Workwear, tools and consumables distributor for professionals."],
  "Alm. Brand": ["Financials", "Danish non-life insurer."],
  "Alma Media Oyj": ["Communication Services", "Finnish digital media and online marketplace group."],
  "Altra Fastigheter": ["Real Estate", "Swedish commercial real-estate company."],
  "Alvotech": ["Health Care", "Iceland-based biosimilars developer."],
  "Amaroq Ltd.": ["Materials", "Greenland-focused gold and strategic-metals explorer."],
  "Ambea": ["Health Care", "Care services for elderly and people with disabilities across the Nordics."],
  "Ambu": ["Health Care", "Danish maker of single-use endoscopes and anaesthesia equipment."],
  "Anora Group Oyj": ["Consumer Staples", "Nordic wine and spirits group (Koskenkorva, Linie aquavit)."],
  "Apotea": ["Consumer Staples", "Sweden's largest online pharmacy."],
  "AQ Group": ["Industrials", "Component manufacturer for industrial customers (transformers, wiring, mechanics)."],
  "Arctic Paper": ["Materials", "Specialty graphical paper producer."],
  "Arion banki": ["Financials", "Icelandic universal bank."],
  "Arjo B": ["Health Care", "Medical devices for patient handling, hygiene and DVT prevention."],
  "Ascelia Pharma": ["Health Care", "Swedish biotech focused on oncology imaging."],
  "Asker Healthcare Group": ["Health Care", "Nordic distributor of medical and care products."],
  "Asmodee Group B": ["Communication Services", "Global publisher and distributor of board games and tabletop hobby."],
  "Aspo Oyj": ["Industrials", "Finnish conglomerate (shipping, energy, trading)."],
  "Atrium Ljungberg B": ["Real Estate", "Swedish urban property owner (offices, retail, residential)."],
  "Attendo": ["Health Care", "Nordic care services for elderly and disabled."],
  "Autoliv SDB": ["Consumer Discretionary", "Global leader in automotive safety (airbags, seatbelts)."],
  "Avanza Bank Holding": ["Financials", "Swedish online savings and brokerage bank."],
  "Avarda Bank": ["Financials", "Swedish payment-services and consumer-finance bank."],
  "Axfood": ["Consumer Staples", "Swedish food retailer (Willys, Hemköp, Snabbgross)."],
  "Bang & Olufsen": ["Consumer Discretionary", "Danish premium audio and TV brand."],
  "Bavarian Nordic": ["Health Care", "Danish vaccines company (smallpox/mpox, rabies, RSV)."],
  "Beijer Alma B": ["Industrials", "Industrial components group (springs, wire products, distribution)."],
  "Bera": ["Financials", "Icelandic investment company."],
  "Bergman & Beving B": ["Industrials", "Trading group serving industry and construction."],
  "Berner Industrier B": ["Industrials", "Industrial distribution of technical products."],
  "Betsson B": ["Consumer Discretionary", "Online sports betting and casino operator."],
  "Better Collective": ["Communication Services", "Digital sports-media and affiliate marketing for iGaming."],
  "BHG Group": ["Consumer Discretionary", "Online home-improvement retailer in the Nordics."],
  "BICO Group": ["Health Care", "Bio-convergence: 3D bioprinting, bioscience automation."],
  "Bilia A": ["Consumer Discretionary", "Nordic auto dealer (Volvo, BMW, Toyota)."],
  "Billerud": ["Materials", "Nordic packaging-paper producer."],
  "BioArctic B": ["Health Care", "Swedish biotech (Alzheimer's, partnered Leqembi with Eisai/Biogen)."],
  "BioGaia B": ["Consumer Staples", "Probiotic supplements for digestive and immune health."],
  "BioInvent International": ["Health Care", "Swedish antibody-based cancer immunotherapy biotech."],
  "Bittium Oyj": ["Technology", "Finnish specialist in secure communications and medical-tech devices."],
  "Bonava B": ["Real Estate", "Nordic and German residential developer."],
  "BONESUPPORT HOLDING": ["Health Care", "Injectable synthetic bone-graft substitutes."],
  "Boozt": ["Consumer Discretionary", "Nordic online fashion retailer."],
  "Bravida Holding": ["Industrials", "Nordic installer of electrical, heating, plumbing and ventilation systems."],
  "Brdr. A & O Johansen B": ["Industrials", "Danish wholesaler of technical installation products."],
  "Brim": ["Consumer Staples", "Icelandic seafood (fishing and processing)."],
  "BTS Group B": ["Consumer Services", "Strategy execution and leadership training consultancy."],
  "Bufab": ["Industrials", "Global supplier of fasteners and C-parts."],
  "Bulten": ["Industrials", "Fastener supplier to the automotive industry."],
  "Bure Equity": ["Financials", "Swedish listed investment company."],
  "Byggmax Group": ["Consumer Discretionary", "Nordic DIY building-materials retailer."],
  "C-RAD B": ["Health Care", "Patient-positioning and motion management for radiotherapy."],
  "Camurus": ["Health Care", "Long-acting injectable therapies, notably for opioid dependence (Buvidal)."],
  "Cantargia": ["Health Care", "Cancer biotech targeting IL1RAP."],
  "CapMan Oyj": ["Financials", "Nordic private-asset manager (PE, infra, real estate)."],
  "Carasent": ["Health Care", "Cloud-based EHR for Nordic primary and outpatient care."],
  "Catella B": ["Financials", "European property advisory and asset management."],
  "Catena": ["Real Estate", "Swedish logistics-property landlord."],
  "CBRAIN": ["Technology", "Government-process software (case-management platform F2)."],
  "CellaVision": ["Health Care", "Automated digital cell-morphology systems for hematology labs."],
  "ChemoMetec": ["Health Care", "Danish cell-counting instruments for life sciences."],
  "Cibus Real Estate": ["Real Estate", "Owner of grocery-anchored properties in the Nordics."],
  "Cinclus Pharma Holding": ["Health Care", "GI-focused drug developer (acid-related disorders)."],
  "Cint Group": ["Communication Services", "Global digital insights and online survey platform."],
  "Citycon Oyj": ["Real Estate", "Owner of urban grocery-anchored shopping centres in the Nordics and Baltics."],
  "Clas Ohlson B": ["Consumer Discretionary", "Swedish hardware/home retailer."],
  "Cloetta B": ["Consumer Staples", "Nordic confectionery (Läkerol, Kexchoklad, Malaco)."],
  "Coor Service Management Hold.": ["Industrials", "Integrated facility management across the Nordics."],
  "Corem Property Group B": ["Real Estate", "Swedish/Nordic commercial-property owner."],
  "CTEK": ["Industrials", "Battery chargers and EV-charging solutions."],
  "CTT Systems": ["Industrials", "Aircraft cabin humidification systems."],
  "D/S Norden": ["Industrials", "Danish dry-cargo and product-tanker shipping."],
  "Dedicare B": ["Health Care", "Healthcare staffing across the Nordics."],
  "Demant": ["Health Care", "Hearing aids, audiology and diagnostics (Oticon)."],
  "DFDS": ["Industrials", "Danish ferry and logistics operator (Channel, North Sea, Baltic)."],
  "Diös Fastigheter": ["Real Estate", "Property owner across northern Swedish cities."],
  "Dometic Group": ["Consumer Discretionary", "Mobile-living products (cooling, sanitation, food prep) for RVs and marine."],
  "Duni": ["Consumer Discretionary", "Premium table-top concepts and sustainable packaging."],
  "Dustin Group": ["Technology", "Nordic IT reseller for SMB and public sector."],
  "Dynavox Group": ["Health Care", "Augmentative and alternative communication devices."],
  "Easor Oyj": ["Industrials", "Finnish energy-systems group."],
  "Eastnine": ["Real Estate", "Owner of Baltic prime offices, listed in Sweden."],
  "Egetis Therapeutics": ["Health Care", "Rare-disease drug development."],
  "Eik fasteignafélag": ["Real Estate", "Icelandic commercial-property owner."],
  "Eimskipafélag Íslands": ["Industrials", "Icelandic shipping and logistics."],
  "Elanders B": ["Industrials", "Supply-chain solutions, print and packaging."],
  "Electrolux B": ["Consumer Discretionary", "Global home-appliance maker."],
  "Electrolux Professional B": ["Industrials", "Professional kitchen and laundry equipment."],
  "Elekta B": ["Health Care", "Radiation oncology and radiosurgery systems."],
  "Embla Medical": ["Health Care", "Iceland-based maker of prosthetics and bracing (formerly Össur)."],
  "Embracer Group B": ["Communication Services", "Video games and entertainment IP holding."],
  "Enad Global 7": ["Communication Services", "Game developer and publisher."],
  "Endomines Finland Oyj": ["Materials", "Gold mining in Finland and the US."],
  "Enea": ["Technology", "Telecom software (5G data management, network security)."],
  "Enento Group Oyj": ["Industrials", "Nordic business and consumer credit-information services."],
  "engcon B": ["Industrials", "Tiltrotators for excavators."],
  "Enity Holding": ["Financials", "Swedish consumer-finance lender."],
  "Eolus B": ["Utilities", "Renewable-power project developer (wind, solar, storage)."],
  "Ependion": ["Technology", "Industrial computers, communications and embedded electronics."],
  "EQL Pharma": ["Health Care", "Niche-generics pharmaceuticals."],
  "Ework Group": ["Industrials", "Consulting and IT-talent supplier."],
  "F-Secure Oyj": ["Technology", "Finnish consumer cybersecurity."],
  "Fabege": ["Real Estate", "Stockholm office-property owner."],
  "Fagerhult Group": ["Industrials", "Professional lighting solutions."],
  "Fasadgruppen Group": ["Industrials", "Nordic façade contractor."],
  "Fastighetsbolaget Emilshus B": ["Real Estate", "Commercial property in southern Sweden."],
  "Fastpartner A": ["Real Estate", "Swedish commercial real estate."],
  "Fenix Outdoor International B": ["Consumer Discretionary", "Outdoor brands (Fjällräven, Tierra, Primus)."],
  "Ferronordic": ["Industrials", "Construction-equipment dealer and services."],
  "Festi": ["Consumer Discretionary", "Icelandic retail group (gas stations, grocery)."],
  "Fingerprint Cards B": ["Technology", "Biometric sensors (fingerprint)."],
  "Finnair Oyj": ["Industrials", "Finnish flag carrier airline."],
  "Fiskars Oyj Abp": ["Consumer Discretionary", "Finnish maker of homeware and consumer goods (Fiskars, Iittala)."],
  "Flerie": ["Health Care", "Life-science holding company."],
  "FLSmidth & Co.": ["Industrials", "Equipment and services for mining and cement industries."],
  "Føroya Banki": ["Financials", "Faroese bank."],
  "G5 Entertainment": ["Communication Services", "Mobile casual-games developer."],
  "Gentoo Media": ["Communication Services", "Digital media for the iGaming industry."],
  "GN Store Nord": ["Health Care", "Hearing instruments and audio communications (Jabra, ReSound)."],
  "Gofore Oyj": ["Technology", "Finnish digital-transformation consultancy."],
  "Green Landscaping Group": ["Industrials", "Outdoor environment services (landscaping, infrastructure)."],
  "GRK Infra Oyj": ["Industrials", "Infrastructure construction (roads, rail)."],
  "Gruvaktiebolaget Viscaria": ["Materials", "Copper mining project in northern Sweden."],
  "Gränges": ["Materials", "Rolled aluminium for HVAC and EV battery applications."],
  "Gubra": ["Health Care", "Preclinical contract research and obesity/metabolic drug development."],
  "H+H International": ["Materials", "Aircrete building blocks producer."],
  "H. Lundbeck B": ["Health Care", "Danish psychiatry- and neurology-focused pharma."],
  "Hacksaw": ["Communication Services", "iGaming content studio."],
  "Hagar": ["Consumer Staples", "Icelandic food wholesaler."],
  "Hampiðjan": ["Industrials", "Icelandic fishing-gear maker (nets, ropes)."],
  "Hansa Biopharma": ["Health Care", "Antibody-cleaving enzyme therapies (kidney transplant, autoimmune)."],
  "HANZA": ["Industrials", "Manufacturing partner for industrial customers."],
  "Harboes Bryggeri B": ["Consumer Staples", "Danish brewery."],
  "Harvia Oyj": ["Consumer Discretionary", "Sauna and spa products."],
  "HEBA B": ["Real Estate", "Stockholm residential property owner."],
  "Heimar": ["Real Estate", "Icelandic property company."],
  "Hemnet Group": ["Communication Services", "Sweden's leading residential property portal."],
  "Hexatronic Group": ["Technology", "Fibre-optic infrastructure products."],
  "HEXPOL B": ["Materials", "Advanced polymer compounds."],
  "Hiab Oyj": ["Industrials", "On-road load-handling equipment (cranes, tail-lifts)."],
  "HMS Networks": ["Technology", "Industrial Internet of Things communications."],
  "Hoist Finance": ["Financials", "European acquirer of non-performing loans."],
  "Hufvudstaden A": ["Real Estate", "Premium Stockholm/Gothenburg city-centre property."],
  "Huhtamäki Oyj": ["Materials", "Sustainable food and consumer packaging."],
  "Humana": ["Health Care", "Care services across the Nordics."],
  "Humble Group": ["Consumer Staples", "Sustainable/better-for-you consumer-goods group."],
  "HusCompagniet": ["Consumer Discretionary", "Danish detached-house builder."],
  "Husqvarna B": ["Industrials", "Outdoor power products (chainsaws, robotic mowers)."],
  "Icelandair Group": ["Industrials", "Icelandic flag carrier airline."],
  "Immunovia": ["Health Care", "Blood-based diagnostics (pancreatic cancer screening)."],
  "Incap Oyj": ["Industrials", "Electronics contract manufacturer."],
  "Infant Bacterial TherapeuticsB": ["Health Care", "Therapy for necrotising enterocolitis in preterm infants."],
  "Instalco": ["Industrials", "Nordic installation services (electrical, HVAC, plumbing)."],
  "Intea Fastigheter B": ["Real Estate", "Owner of public-sector properties (universities, courts)."],
  "International Petroleum Corp.": ["Energy", "Oil and gas producer (Canada, Malaysia, France)."],
  "Intrum": ["Financials", "European credit-management and debt-collection services."],
  "INVISIO": ["Industrials", "Communication systems for defence and security."],
  "Inwido": ["Industrials", "Nordic and European windows and doors."],
  "Isofol Medical": ["Health Care", "Oncology drug development."],
  "ISS": ["Industrials", "Global facility services."],
  "ITAB Shop Concept": ["Industrials", "Retail store interiors and check-out systems."],
  "JBT Marel Corp.": ["Industrials", "Food-processing technology and solutions."],
  "Jeudan": ["Real Estate", "Copenhagen office property owner and operator."],
  "JM": ["Consumer Discretionary", "Nordic residential developer."],
  "John Mattson Fastighetsföret.": ["Real Estate", "Stockholm residential property owner."],
  "Jyske Bank": ["Financials", "Danish full-service bank."],
  "K-Fast Holding B": ["Real Estate", "Cost-efficient residential property developer."],
  "Kaldalón": ["Real Estate", "Icelandic property company."],
  "Kalmar Oyj B": ["Industrials", "Container and cargo handling equipment."],
  "Kamux Oyj": ["Consumer Discretionary", "Used-car retailer."],
  "Karnell Group B": ["Industrials", "Niche industrial holding group."],
  "Karnov Group": ["Communication Services", "Legal and tax information services."],
  "Kemira Oyj": ["Materials", "Specialty chemicals (water, pulp & paper)."],
  "Kempower Oyj": ["Industrials", "Fast EV chargers for trucks and buses."],
  "Kinnevik B": ["Financials", "Listed investment company focused on growth tech."],
  "KlaraBo Sverige B": ["Real Estate", "Residential property owner in Swedish growth cities."],
  "Knowit": ["Technology", "Nordic IT and design consultancy."],
  "Kvika banki": ["Financials", "Icelandic challenger bank."],
  "Lagercrantz Group B": ["Industrials", "Niche tech and components group."],
  "Lassila & Tikanoja": ["Industrials", "Environmental services and industrial cleaning."],
  "Latour B": ["Financials", "Listed investment company with industrial holdings."],
  "Lime Technologies": ["Technology", "CRM software for Nordic SMB."],
  "Lindab International": ["Industrials", "Ventilation systems and ductwork."],
  "Lindex Group Oyj": ["Consumer Discretionary", "Nordic women's fashion retail."],
  "Logistea B": ["Real Estate", "Logistics and industrial properties in Sweden."],
  "Loomis": ["Industrials", "Cash-handling and ATM services."],
  "Lumo Kodit Oyj": ["Real Estate", "Finnish residential rental owner."],
  "Lundbergföretagen B": ["Financials", "Listed family investment company."],
  "Lundin Gold": ["Materials", "Gold producer (Fruta del Norte, Ecuador)."],
  "Lundin Mining Corporation": ["Materials", "Diversified base-metals miner."],
  "Luotea Plc": ["Financials", "Consumer-finance lender."],
  "Maha Capital": ["Energy", "Oil and gas E&P focused on Brazil."],
  "Mandatum": ["Financials", "Finnish wealth and life-insurance group."],
  "Marimekko Oyj": ["Consumer Discretionary", "Finnish design and lifestyle brand."],
  "Matas": ["Consumer Discretionary", "Danish beauty and personal-care retailer."],
  "MedCap": ["Health Care", "Nordic medical-device and pharma group."],
  "Medicover B": ["Health Care", "Pan-European clinics and diagnostic labs."],
  "MEKO": ["Consumer Discretionary", "Nordic auto-parts wholesaler (Mekonomen)."],
  "Meren Energy": ["Energy", "African-focused oil and gas (formerly Africa Oil)."],
  "Metsä Board Oyj B": ["Materials", "Premium folding boxboard and white kraftliner."],
  "Mildef Group": ["Industrials", "Rugged electronics for defence."],
  "Mips": ["Consumer Discretionary", "Brain-protection system for helmets."],
  "Moberg Pharma": ["Health Care", "Topical OTC pharmaceuticals."],
  "Modern Times Group B": ["Communication Services", "Mobile-games publisher (MTG)."],
  "Momentum Group B": ["Industrials", "Industrial components and consumables."],
  "MT Højgaard Holding": ["Industrials", "Danish construction group."],
  "Munters Group": ["Industrials", "Climate-control solutions (data centres, food production)."],
  "Musti Group Oyj": ["Consumer Discretionary", "Nordic pet-care retailer."],
  "Mycronic": ["Industrials", "Electronics-assembly equipment and mask writers for displays."],
  "NCAB Group": ["Technology", "Printed-circuit-board sourcing partner."],
  "NCC B": ["Industrials", "Nordic construction and infrastructure."],
  "Nederman Holding": ["Industrials", "Industrial air filtration."],
  "Nelly Group": ["Consumer Discretionary", "Online fashion retailer."],
  "Neobo Fastigheter": ["Real Estate", "Swedish residential property owner."],
  "Net Insight B": ["Technology", "Media networking and live-content transport."],
  "Netcompany Group": ["Technology", "Danish digital-transformation consultancy."],
  "Netel Holding": ["Industrials", "Critical-infrastructure contractor (telecom, power)."],
  "New Wave B": ["Consumer Discretionary", "Brand group (Craft, Cutter & Buck, Orrefors)."],
  "Nightingale Health Oyj B": ["Health Care", "Blood-biomarker analytics for preventive health."],
  "Nilörngruppen B": ["Consumer Discretionary", "Branding and trims for apparel."],
  "Nivika Fastigheter B": ["Real Estate", "Residential and commercial property in southern Sweden."],
  "NNIT": ["Technology", "Danish IT services for life sciences."],
  "NOBA Bank Group": ["Financials", "Nordic consumer-finance bank."],
  "Nobia": ["Consumer Discretionary", "Kitchen-cabinet manufacturer."],
  "Nokian Renkaat Oyj": ["Consumer Discretionary", "Finnish winter and all-season tyre maker."],
  "Nolato B": ["Materials", "Polymer products for medical and industrial use."],
  "Nordnet": ["Financials", "Pan-Nordic online savings and brokerage bank."],
  "Norion Bank": ["Financials", "Swedish corporate and consumer bank."],
  "North Media": ["Communication Services", "Danish distribution and digital marketplaces."],
  "NOTE": ["Industrials", "Electronics manufacturing services."],
  "Nova Klúbburinn": ["Communication Services", "Icelandic telecom (mobile, broadband)."],
  "NP3 Fastigheter": ["Real Estate", "Commercial-property owner in northern Sweden."],
  "NTG Nordic Transport Group": ["Industrials", "Asset-light freight forwarder."],
  "Oculis Holding": ["Health Care", "Ophthalmology biopharma."],
  "OEM International B": ["Industrials", "Trading of industrial components."],
  "Olvi Oyj A": ["Consumer Staples", "Finnish brewery group (beer, soft drinks)."],
  "Oma Säästöpankki Oyj": ["Financials", "Finnish regional savings bank."],
  "Oncopeptides": ["Health Care", "Cancer drug development (multiple myeloma)."],
  "Optomed Oyj": ["Health Care", "Handheld ophthalmic imaging devices."],
  "Oriola Oyj": ["Health Care", "Pharmaceutical distribution in Finland and Sweden."],
  "Orrön Energy": ["Utilities", "Listed renewable-energy producer (wind)."],
  "Outokumpu Oyj": ["Materials", "Stainless steel producer."],
  "Ovzon": ["Communication Services", "Satellite-based mobile broadband for defence."],
  "Pandox B": ["Real Estate", "Owner and operator of hotel properties."],
  "Peab B": ["Industrials", "Nordic construction and civil engineering."],
  "Per Aarsleff Holding B": ["Industrials", "Danish ground-works and civil-engineering contractor."],
  "Pierce Group": ["Consumer Discretionary", "Online motorcycle-gear retailer."],
  "Pihlajalinna Oyj": ["Health Care", "Finnish private healthcare operator."],
  "Platzer Fastigheter Holding B": ["Real Estate", "Gothenburg commercial property."],
  "Ponsse Oyj 1": ["Industrials", "Cut-to-length forestry machines."],
  "Posti Group": ["Industrials", "Finnish postal and logistics operator."],
  "PowerCell Sweden": ["Industrials", "Hydrogen fuel-cell systems."],
  "Precise Biometrics": ["Technology", "Mobile biometric software."],
  "Prevas B": ["Technology", "Industrial digitalisation consultancy."],
  "Pricer B": ["Technology", "Electronic shelf-label systems for retail."],
  "Prisma Properties": ["Real Estate", "Retail-property owner in Sweden."],
  "Proact IT Group": ["Technology", "Nordic IT-infrastructure services."],
  "Puuilo Oyj": ["Consumer Discretionary", "Finnish discount hardware retailer."],
  "Q-Linea": ["Health Care", "Rapid microbiology diagnostics."],
  "Qt Group Oyj": ["Technology", "Cross-platform application development software."],
  "Raisio Oyj Vaihto-osake": ["Consumer Staples", "Finnish plant-based foods (Benecol)."],
  "Ratos B": ["Financials", "Listed investment company (Nordic mid-cap)."],
  "RaySearch Laboratories B": ["Health Care", "Treatment-planning software for radiation therapy."],
  "Reitir fasteignafélag": ["Real Estate", "Icelandic commercial-property owner."],
  "Rejlers B": ["Industrials", "Nordic engineering consultancy."],
  "Relais Group Oyj": ["Consumer Discretionary", "Heavy-vehicle aftermarket parts."],
  "Remedy Entertainment Oyj": ["Communication Services", "AAA game studio (Control, Alan Wake)."],
  "Revenio Group Oyj": ["Health Care", "Glaucoma screening devices."],
  "Royal UNIBREW": ["Consumer Staples", "Danish brewer (Faxe Kondi, Royal)."],
  "Rusta": ["Consumer Discretionary", "Nordic value retailer of home and leisure goods."],
  "RVRC Holding": ["Consumer Discretionary", "Direct-to-consumer outdoor brand (Revolution Race)."],
  "Röko B": ["Financials", "Acquirer of niche profitable Nordic businesses."],
  "Samhällsbyggnadsbo. i Norden B": ["Real Estate", "Owner of community-service properties (SBB)."],
  "Saniona": ["Health Care", "Rare-disease drug developer."],
  "Sanoma Oyj": ["Communication Services", "Finnish learning and media group."],
  "Scandi Standard": ["Consumer Staples", "Nordic chicken-meat producer."],
  "Scandic Hotels Group": ["Consumer Discretionary", "Nordic hotel operator."],
  "Scandinavian Tobacco Group": ["Consumer Staples", "Cigars, pipe tobacco and accessories."],
  "Scanfil Oyj": ["Industrials", "Electronics contract manufacturer."],
  "Schouw & Co.": ["Industrials", "Danish industrial conglomerate (BioMar, GPV)."],
  "Sdiptech B": ["Industrials", "Niche infrastructure-tech group."],
  "SECTRA B": ["Health Care", "Medical imaging IT and cybersecurity."],
  "Sedana Medical": ["Health Care", "Inhaled sedation for ICU patients."],
  "Senzime": ["Health Care", "Patient-monitoring devices."],
  "Sinch": ["Communication Services", "Cloud messaging and customer-engagement APIs."],
  "Sivers Semiconductors": ["Technology", "RF and photonics chips (5G, satellite)."],
  "SJF Bank": ["Financials", "Danish savings bank."],
  "Sjóvá-Almennar tryggingar": ["Financials", "Icelandic non-life insurer."],
  "Skagi": ["Financials", "Icelandic insurance and asset management."],
  "Skel fjárfestingafélag": ["Financials", "Icelandic investment company."],
  "SkiStar B": ["Consumer Discretionary", "Operator of Nordic alpine ski resorts."],
  "Skjern Bank": ["Financials", "Danish regional bank."],
  "Sleep Cycle": ["Health Care", "Sleep-tracking app subscription."],
  "Solar B": ["Industrials", "Distributor of electrical, plumbing and HVAC products."],
  "Solid Försäkringsaktiebolag": ["Financials", "Swedish niche insurer."],
  "SP Group": ["Materials", "Plastic-product manufacturer."],
  "SSH Communications Security": ["Technology", "Encrypted connectivity and PAM software."],
  "Stendörren Fastigheter B": ["Real Estate", "Light-industrial property owner."],
  "Stenhus Fastigheter i Norden": ["Real Estate", "Mixed-use property owner in Sweden."],
  "Stillfront Group": ["Communication Services", "Free-to-play mobile and browser games publisher."],
  "Storskogen Group B": ["Industrials", "Diversified acquirer of small-and-medium Nordic businesses."],
  "Studsvik": ["Industrials", "Nuclear-fuel and waste-management services."],
  "Sveafastigheter": ["Real Estate", "Swedish residential developer/owner."],
  "Svedbergs Group B": ["Consumer Discretionary", "Bathroom-furniture maker."],
  "SWECO B": ["Industrials", "Engineering and architecture consultancy."],
  "Swedish Logistic Property B": ["Real Estate", "Logistics-property owner in Sweden."],
  "SynAct Pharma": ["Health Care", "Inflammation-focused biopharma."],
  "Synsam": ["Consumer Discretionary", "Nordic optical retailer."],
  "Systemair": ["Industrials", "Ventilation products."],
  "Síldarvinnslan": ["Consumer Staples", "Icelandic pelagic-fish processor."],
  "Síminn": ["Communication Services", "Icelandic telecom operator."],
  "Sýn": ["Communication Services", "Icelandic telecom and media (Vodafone Iceland)."],
  "Taaleri Oyj": ["Financials", "Finnish alternative-asset manager."],
  "Talenom Oyj": ["Industrials", "Accounting services for SMB."],
  "Terveystalo Oyj": ["Health Care", "Finnish private healthcare provider."],
  "Thule Group": ["Consumer Discretionary", "Roof racks, bike carriers and outdoor gear."],
  "Tieto Oyj": ["Technology", "Nordic IT services (TietoEvry)."],
  "Tobii": ["Technology", "Eye-tracking hardware and software."],
  "Tokmanni Group Oyj": ["Consumer Discretionary", "Finnish discount variety retailer."],
  "TORM A": ["Energy", "Product-tanker shipping."],
  "Transtema Group": ["Industrials", "Communications-infrastructure contractor."],
  "TRATON": ["Industrials", "Heavy commercial vehicles (Scania, MAN, Navistar)."],
  "Trianon B": ["Real Estate", "Residential and commercial property in Malmö."],
  "Trifork Group": ["Technology", "Software-development house."],
  "Troax Group": ["Industrials", "Mesh-panel safety enclosures."],
  "Truecaller B": ["Technology", "Caller-identification app."],
  "UIE Plc": ["Consumer Staples", "Listed investment holding (palm-oil and food assets)."],
  "Vaisala Oyj A": ["Industrials", "Weather and environmental measurement instruments."],
  "VBG GROUP B": ["Industrials", "Truck equipment and air-treatment industrial group."],
  "Verkkokauppa.com Oyj": ["Consumer Discretionary", "Finnish online electronics retailer."],
  "Vestum": ["Industrials", "Infrastructure services group (water, civil works)."],
  "Viaplay Group B": ["Communication Services", "Nordic streaming and broadcasting (NENT)."],
  "Vicore Pharma Holding": ["Health Care", "Rare-lung-disease biotech."],
  "Vimian Group": ["Health Care", "Global animal-health products."],
  "Vitec Software Group B": ["Technology", "Vertical-market software acquirer."],
  "Vitrolife": ["Health Care", "IVF media and devices."],
  "VNV Global": ["Financials", "Listed venture-capital investor."],
  "Volati": ["Industrials", "Nordic industrial acquirer."],
  "Volvo Car B": ["Consumer Discretionary", "Premium and electric carmaker."],
  "Wallenstam B": ["Real Estate", "Residential and commercial property in Gothenburg/Stockholm."],
  "Wihlborgs Fastigheter": ["Real Estate", "Property owner in the Öresund region."],
  "Xbrane Biopharma": ["Health Care", "Biosimilars developer."],
  "Xspray Pharma": ["Health Care", "Cancer-drug reformulation specialist."],
  "Xvivo Perfusion": ["Health Care", "Organ-preservation devices for transplantation."],
  "YIT Oyj": ["Industrials", "Finnish construction (residential, infrastructure)."],
  "Yubico": ["Technology", "Hardware security keys (YubiKey)."],
  "Ísfélag": ["Consumer Staples", "Icelandic seafood processor."],
  "Íslandsbanki": ["Financials", "Icelandic universal bank."],
  "Öresund": ["Financials", "Listed Swedish investment company."],
};

// Keyword-based inference for the long tail.
function inferSector(name) {
  const n = name.toLowerCase();
  if (/(pharma|bio|therapeut|medical|medic|health|biotech|pharm)/.test(n)) return "Health Care";
  if (/(bank|banki|pankki)/.test(n)) return "Financials";
  if (/(fastighet|properties|property|real estate|fasteign|kodit)/.test(n)) return "Real Estate";
  if (/(software|tech|technologies|telecom|cyber)/.test(n)) return "Technology";
  if (/(media|games|gaming|entertainment|tv|press)/.test(n)) return "Communication Services";
  if (/(retail|fashion|brand|shop|store|cars?|auto)/.test(n)) return "Consumer Discretionary";
  if (/(food|brewer|seafood|fisk|fish|tobacco|cloetta|olvi)/.test(n)) return "Consumer Staples";
  if (/(industri|industrial|construction|building|engineer|logistics|transport|shipping)/.test(n)) return "Industrials";
  if (/(energy|oil|gas|wind|solar)/.test(n)) return "Energy";
  if (/(materials|mining|steel|paper|chem|aluminium|gold|copper)/.test(n)) return "Materials";
  if (/(insur|capital|equity|invest|holding|fond)/.test(n)) return "Financials";
  return "Other";
}

let withOverride = 0;
let withInference = 0;
for (const s of stocks) {
  const exact = overrides[s.name];
  if (exact) {
    s.sector = exact[0];
    s.description = exact[1];
    withOverride++;
  } else {
    s.sector = inferSector(s.name);
    s.description = `Nordic listed company on ${s.exchange || s.country}. Trades in ${s.ccy}. Sector inferred from name; verify on the company's investor-relations site.`;
    withInference++;
  }
}

fs.writeFileSync(file, JSON.stringify(stocks, null, 2) + "\n");
console.log(`Enriched ${stocks.length} stocks: ${withOverride} curated, ${withInference} keyword-inferred.`);

const bySector = stocks.reduce((acc, s) => {
  acc[s.sector] = (acc[s.sector] || 0) + 1;
  return acc;
}, {});
console.log("By sector:", bySector);
